
var actual_map;

//function that display the form to create a new map
function generateMapForm(){
		  
	//if the form to create map already exists (button has been clicked)
	if($('#mapcreationbox').length){
		//we remove it
		$('#mapcreationbox').remove();
	}
	else{
		//else we create it
		var box = "<div id=mapcreationbox>";
		box += "<table><tr><td>Map's name : </td><td><input type=text name=mapname /></td></tr>";
		box += "<tr><td>Description : </td><td><textarea rows =3 cols =20 /></td></tr>";
		box += "<tr><td colspan=2><input type=button name=createmap value=Create onclick=createMapFromForm() /></td></tr></table>";
		box += "</div>";
		$('input[name=createmap]').after(box);
	}
}

//function that create a new map using the form generated by the function generateMapForm
function createMapFromForm(){
	
	
	var name = $('input[name=mapname]').val();
	var description = $('textarea').val();
	
	actual_map = Map.createMap(name, description);
	alert(actual_map.toXML());
	
	var head = "<h2>"+name+"</h2><i>"+description+"</i>";
	
	var options = "<input type=button name=createlayer value=\"Add Layer\" onclick=createLayerForm() /input></br>";
	options += "<input type=button name=loadlayer value=\"Load an existing layer\" /input></br>";
	
	var box = generateLayersList();
	
	$('#options').html(options);
	$('#head').html(head);
	$('#box').html(box);
	
}

//function that return the list of all the layer actually on the map (html format)
function generateLayersList(){
	
	var layerlist = "Layers : </br>";
	for(var i = 0; i<actual_map.getLayers().length; i++){
		layerlist += actual_map.getLayer(i)._name+" ( "+actual_map.getLayer(i)._type+" ) </br>";
	}
	
	return layerlist;
}

//function that generate the form to create a new layer on the map
function createLayerForm(){
	
	//if the form already exists (button has been clicked)
	if($('#layercreationbox').length){
		//we delete it
		$('#layercreationbox').remove();
	}
	
	else{
		//else we create it
		var box = "<div id=layercreationbox>";
		box += "<table><tr><td>Layer's name : </td><td><input type=text name=layername /></td></tr>";
		box += "<tr><td>Description : </td><td><textarea rows =3 cols =20 /></td></tr>";
		box += "<tr><td>Type : </td><td><select name=layertype><option>Dot<option>Path</select></td></tr>";
		box += "<tr><td colspan=2><input type=button name=createmap value=Create onclick=createLayerFromForm() /></td></tr></table>";
		box += "</div>";
		$('input[name=createlayer]').after(box);
	}
}

//function that create a new layer on the map using the form generated by the function createLayerForm()
function createLayerFromForm(){

	var name = $('input[name=layername]').val();
	var description = $('textarea').val();
	var type = $('select').val();
	var layer = Layer.createLayer(name, description, type);
	
	actual_map.addLayer(layer);
	alert(actual_map.toXML());
	
	$('#layercreationbox').remove();
	$('#box').html(generateLayersList());
	
	
}